# Generated by Django 4.2.7 on 2026-08-25 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_session_id', models.BigIntegerField(help_text='Local SQLite Sessions.Id on the reporting machine (unique per-device only).')),
                ('username', models.CharField(help_text='Username shown in the GapsSight session at the time it ran.', max_length=150)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, help_text='Null sessions are never synced -- see build_sync_payload/the sync view, which only accept sessions the client has already ended.', null=True)),
                ('total_active_seconds', models.PositiveIntegerField(default=0)),
                ('total_afk_seconds', models.PositiveIntegerField(default=0)),
                ('total_blocked_seconds', models.PositiveIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='The authenticated employee/admin whose desktop app reported this session.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivityGateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('mouse_x', models.IntegerField(default=0)),
                ('mouse_y', models.IntegerField(default=0)),
                ('mouse_moved', models.BooleanField(default=False)),
                ('key_pressed', models.BooleanField(default=False)),
                ('process_name', models.CharField(blank=True, default='', max_length=255)),
                ('window_title', models.CharField(blank=True, default='', max_length=500)),
                ('is_allowed_app', models.BooleanField(default=False)),
                ('is_present', models.BooleanField(default=False)),
                ('timer_running', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_checks', to='activity.activitysession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActivityStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='activity.activitysession')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='activity_ac_session_a596a6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='activitysession',
            index=models.Index(fields=['owner', 'start_time'], name='activity_ac_owner_i_e171e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='activitysession',
            constraint=models.UniqueConstraint(fields=('owner', 'client_session_id'), name='unique_activitysession_owner_client_id'),
        ),
        migrations.AddIndex(
            model_name='activitygatecheck',
            index=models.Index(fields=['session', 'timestamp'], name='activity_ac_session_2bc187_idx'),
        ),
    ]
