# Generated by Django 4.2.7 on 2026-08-25 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vscode_project', 'VS Code project'), ('browser_tab', 'Browser tab')], max_length=20)),
                ('value', models.CharField(help_text="Text matched as a case-insensitive substring against the active window title, e.g. 'GapsSight' or 'GapsSight – Figma'.", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive entries are kept for reference but left out of sync.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_apps_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'value'],
            },
        ),
        migrations.AddConstraint(
            model_name='allowedapp',
            constraint=models.UniqueConstraint(fields=('kind', 'value'), name='unique_allowedapp_kind_value'),
        ),
    ]
