# Generated by Django 6.1 on 2026-08-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeManagement',
            fields=[
            ],
            options={
                'verbose_name': 'Employee (management)',
                'verbose_name_plural': '🧑\u200d💼 Employee Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employees.employee',),
        ),
        migrations.CreateModel(
            name='UserManagement',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': '👤 User Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('employees.employee',),
        ),
    ]
